apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redirector
  labels:
    app: redirector
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redirector
  template:
    metadata:
      annotations:
        targetGroupArn: "MY_TARGET_GROUP_ARN"
        targetPort: 80
        logTargetInfo: "true"
      labels:
        app: redirector
    spec:
      containers:
      - name: redirectory
        image: bashism/http-to-https:latest
        env:
        - name: GENERATE_CERT
          value: "true"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: redirector
spec:
  selector:
    app: redirector
  ports:
  - port: 80
  type: NodePort
