apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: log-target-data
spec:
  resources:
  - apiVersion: v1
    resource: pods
    annotationSelector:
      matchExpressions:
      - {key: logTargetInfo, operator: Exists}
  hooks:
    sync:
      webhook:
        url: http://register-targets.metacontroller.svc.cluster.local/log-info

---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: DecoratorController
metadata:
  name: register-target
spec:
  resources:
  - apiVersion: v1
    resource: pods
    annotationSelector:
      matchExpressions:
      - {key: targetGroupArn, operator: Exists}
      - {key: targetPort, operator: Exists}
  hooks:
    sync:
      webhook:
        url: http://register-targets.metacontroller.svc.cluster.local/register
    finalize:
      webhook:
        url: http://register-targets.metacontroller.svc.cluster.local/deregister

---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: register-targets
  namespace: metacontroller
spec:
  template:
    metadata:
      labels:
        app: register-targets
      annotations:
        iam.amazonaws.com/role: {{ .Values.role }}
    spec:
      containers:
      - name: hooks
        image: {{ .Values.image }}
        imagePullPolicy: Always
        env:
        - name: AWS_REGION
          value: {{ .Values.region }}
        command: ["/bin/sh", "-ec", "while :; do echo '.'; sleep 5 ; done"]
---
apiVersion: v1
kind: Service
metadata:
  name: register-targets
  namespace: metacontroller
spec:
  selector:
    app: register-targets
  ports:
  - port: 80
